// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yatpknkcmzlxzszmsslb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhdHBrbmtjbXpseHpzem1zc2xiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0NjE3MjYsImV4cCI6MjA2ODAzNzcyNn0.02kkv-RqPFZF3mHmNhkdAy6FmKNTKiA22J5qw0bLNTA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});